### ISSUE TITLE
Url Rewriter wrong Href values

### ISSUE THREAD

**Issue by naupadnara** [sethyates/urlrewriter#3]
Hello,
          I am using url rewriter on my master page. (ASP.NET 4.0). I have mapped a url with e.g:
&lt;rewrite url="~/abc.aspx" to="~/folder1/xyz.aspx"/&gt;

When I go on http://domain/abc.aspx than all my URLs under folder-1 are having wrong href values. E.g for accessing mypage.aspx under folder-1, following happens:

Should be: http://domain/folder-1/mypage.aspx

But in reality it is: http://domain/mypage.aspx

Help me...

**Comment by sethyates** [comment]
It doesn't rewrite your HTML for you.  It rewrites requests for URL's to different paths.
